### ISSUE TITLE
UnicodeDecodeError on exec under Singularity's img

### ISSUE THREAD

**Issue by tguegan** [jerabaul29/Cylinder2DFlowControlDRL#1]
Hi,

I've tried to run your code on my computer and to make everything easier I wanted to use your singularity container. Everything is working fine for the container but when I run the code I got this error :

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)`

And here is the full traceback :

`Traceback (most recent call last):
  File "single_runner.py", line 2, in <module>
    from env import resume_env
  File "/home/***/Cylinder2DFlowControlWithRL/baseline_flow/env.py", line 10, in <module>
    from Env2DCylinder import Env2DCylinder
  File "/home/***/Cylinder2DFlowControlWithRL/baseline_flow/../Env2DCylinder.py", line 3, in <module>
    from tensorforce.environments import Environment
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/environments/__init__.py", line 17, in <module>
    from tensorforce.environments.environment import Environment
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/environments/environment.py", line 22, in <module>
    import tensorforce.util
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 19, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 82, in <module>
    from tensorflow.python.estimator import estimator_lib as estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator_lib.py", line 41, in <module>
    from tensorflow.python.estimator.inputs import inputs
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/inputs.py", line 22, in <module>
    from tensorflow.python.estimator.inputs.numpy_io import numpy_input_fn
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/numpy_io.py", line 26, in <module>
    from tensorflow.python.estimator.inputs.queues import feeding_functions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 80, in <module>
    import pandas.plotting._core as gfx
  File "/usr/local/lib/python2.7/dist-packages/pandas/plotting/__init__.py", line 11, in <module>
    from pandas.plotting._core import boxplot
  File "/usr/local/lib/python2.7/dist-packages/pandas/plotting/_core.py", line 45, in <module>
    from pandas.plotting import _converter
  File "/usr/local/lib/python2.7/dist-packages/pandas/plotting/_converter.py", line 8, in <module>
    import matplotlib.units as units
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1133, in <module>
    rcParams = rc_params()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 967, in rc_params
    fname = matplotlib_fname()
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 782, in matplotlib_fname
    cwd = os.getcwdu()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)`

Any help will be much appreciated !

Thibaut

**Comment by jerabaul29** [comment]
Ok, I never encountered something like that before (and our code has been tested on several machines at different institutions).

- What command did you issue to get this? Is it possible that you used ```python3``` instead of ```python``` (the code is python 2).

- This seems to be somehow related to matplotlib and some stuff with the name of the directory (by reading the last entry in the error log). Is it possible that you are running the code on a windows machine and that some of your path names are not unix-friendly?

- Otherwise this is very strange. It seems that the error is known as ```UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)``` gets several hits in google, but I did not have the problem myself. If I cannot reproduce it you will have to solve it yourself...

**Comment by tguegan** [comment]
So yeah you were right ! I'm using a distribution firstly installed in french then added package to use it in english but my "Downloads" folder was still called "Téléchargements"...

The code is working fine now, thank you !

**Comment by jerabaul29** [comment]
Perfect! This is what I expected ;)
